var path = require('path');

var SOURCE_DIRECTORY = 'src';
var DEST_DIRECTORY = 'dest';

var SHARED_SUBDIRECTORY = 'shared';
var CLIENT_SUBDIRECTORY = 'client';
var SERVER_SUBDIRECTORY = 'server';

var SCRIPT_SUBDIRECTORY = 'script';
var STYLE_SUBDIRECTORY = 'style';
var MEDIA_SUBDIRECTORY = 'media';
var VIEW_SUBDIRECTORY = 'view';

var MAIN_SCRIPT = 'main.js';
var MAIN_STYLE = 'screen.less';

var SOURCE_SCRIPT = path.join(SOURCE_DIRECTORY, CLIENT_SUBDIRECTORY, SCRIPT_SUBDIRECTORY);
var SOURCE_STYLE = path.join(SOURCE_DIRECTORY, CLIENT_SUBDIRECTORY, STYLE_SUBDIRECTORY);
var SOURCE_MEDIA = path.join(SOURCE_DIRECTORY, CLIENT_SUBDIRECTORY, MEDIA_SUBDIRECTORY);
var SOURCE_SERVER = path.join(SOURCE_DIRECTORY, SERVER_SUBDIRECTORY);
var SOURCE_SHARED_VIEW = path.join(SOURCE_DIRECTORY, SHARED_SUBDIRECTORY, VIEW_SUBDIRECTORY);

var DEST_SCRIPT = path.join(DEST_DIRECTORY, CLIENT_SUBDIRECTORY, SCRIPT_SUBDIRECTORY);
var DEST_STYLE = path.join(DEST_DIRECTORY, CLIENT_SUBDIRECTORY, STYLE_SUBDIRECTORY);
var DEST_MEDIA = path.join(DEST_DIRECTORY, CLIENT_SUBDIRECTORY, MEDIA_SUBDIRECTORY);
var DEST_SERVER = path.join(DEST_DIRECTORY, SERVER_SUBDIRECTORY);
var DEST_SERVER_VIEW = path.join(DEST_DIRECTORY, SERVER_SUBDIRECTORY, VIEW_SUBDIRECTORY);

module.exports = {
    // Compilation Files
    CLIENT_SCRIPTS: [
        'main.js',
        '112015Visualization.jsx'
    ],

    // Primary Directories
    SOURCE_DIRECTORY: SOURCE_DIRECTORY,
    DEST_DIRECTORY: DEST_DIRECTORY,

    MAIN_STYLE: MAIN_STYLE,

    // Subdirectories
    SOURCE_SCRIPT: SOURCE_SCRIPT,
    SOURCE_STYLE: SOURCE_STYLE,
    SOURCE_MEDIA: SOURCE_MEDIA,
    SOURCE_SERVER: SOURCE_SERVER,
    SOURCE_SHARED_VIEW: SOURCE_SHARED_VIEW,

    SOURCE_STYLE_MAIN: path.join(SOURCE_STYLE, MAIN_STYLE),
    SOURCE_SCRIPT_MAIN: path.join(SOURCE_SCRIPT, MAIN_SCRIPT),
    SOURCE_SERVER_MAIN: path.join(SOURCE_SERVER, MAIN_SCRIPT),

    DEST_SCRIPT: DEST_SCRIPT,
    DEST_STYLE: DEST_STYLE,
    DEST_MEDIA: DEST_MEDIA,
    DEST_SERVER: DEST_SERVER,
    DEST_SERVER_VIEW: DEST_SERVER_VIEW,

    DEST_STYLE_MAIN: path.join(DEST_STYLE, MAIN_STYLE),
    DEST_SCRIPT_MAIN: path.join(DEST_SCRIPT, MAIN_SCRIPT),
    DEST_SERVER_MAIN: path.join(DEST_SERVER, MAIN_SCRIPT)
};